/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedPersonasRouteImport } from './routes/_authenticated/personas'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiDebateStreamRouteImport } from './routes/api/debate.stream'
import { Route as AuthenticatedDebatesIdRouteImport } from './routes/_authenticated/debates.$id'
import { Route as AuthenticatedDebatesIdPresentRouteImport } from './routes/_authenticated/debates.$id.present'
import { Route as AuthenticatedDebatesIdEditRouteImport } from './routes/_authenticated/debates.$id.edit'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPersonasRoute = AuthenticatedPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiDebateStreamRoute = ApiDebateStreamRouteImport.update({
  id: '/api/debate/stream',
  path: '/api/debate/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDebatesIdRoute = AuthenticatedDebatesIdRouteImport.update({
  id: '/debates/$id',
  path: '/debates/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDebatesIdPresentRoute =
  AuthenticatedDebatesIdPresentRouteImport.update({
    id: '/present',
    path: '/present',
    getParentRoute: () => AuthenticatedDebatesIdRoute,
  } as any)
const AuthenticatedDebatesIdEditRoute =
  AuthenticatedDebatesIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AuthenticatedDebatesIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new': typeof AuthenticatedNewRoute
  '/personas': typeof AuthenticatedPersonasRoute
  '/debates/$id': typeof AuthenticatedDebatesIdRouteWithChildren
  '/api/debate/stream': typeof ApiDebateStreamRoute
  '/debates/$id/edit': typeof AuthenticatedDebatesIdEditRoute
  '/debates/$id/present': typeof AuthenticatedDebatesIdPresentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new': typeof AuthenticatedNewRoute
  '/personas': typeof AuthenticatedPersonasRoute
  '/debates/$id': typeof AuthenticatedDebatesIdRouteWithChildren
  '/api/debate/stream': typeof ApiDebateStreamRoute
  '/debates/$id/edit': typeof AuthenticatedDebatesIdEditRoute
  '/debates/$id/present': typeof AuthenticatedDebatesIdPresentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/personas': typeof AuthenticatedPersonasRoute
  '/_authenticated/debates/$id': typeof AuthenticatedDebatesIdRouteWithChildren
  '/api/debate/stream': typeof ApiDebateStreamRoute
  '/_authenticated/debates/$id/edit': typeof AuthenticatedDebatesIdEditRoute
  '/_authenticated/debates/$id/present': typeof AuthenticatedDebatesIdPresentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/new'
    | '/personas'
    | '/debates/$id'
    | '/api/debate/stream'
    | '/debates/$id/edit'
    | '/debates/$id/present'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/new'
    | '/personas'
    | '/debates/$id'
    | '/api/debate/stream'
    | '/debates/$id/edit'
    | '/debates/$id/present'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/new'
    | '/_authenticated/personas'
    | '/_authenticated/debates/$id'
    | '/api/debate/stream'
    | '/_authenticated/debates/$id/edit'
    | '/_authenticated/debates/$id/present'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiDebateStreamRoute: typeof ApiDebateStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/personas': {
      id: '/_authenticated/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof AuthenticatedPersonasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/debate/stream': {
      id: '/api/debate/stream'
      path: '/api/debate/stream'
      fullPath: '/api/debate/stream'
      preLoaderRoute: typeof ApiDebateStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/debates/$id': {
      id: '/_authenticated/debates/$id'
      path: '/debates/$id'
      fullPath: '/debates/$id'
      preLoaderRoute: typeof AuthenticatedDebatesIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debates/$id/present': {
      id: '/_authenticated/debates/$id/present'
      path: '/present'
      fullPath: '/debates/$id/present'
      preLoaderRoute: typeof AuthenticatedDebatesIdPresentRouteImport
      parentRoute: typeof AuthenticatedDebatesIdRoute
    }
    '/_authenticated/debates/$id/edit': {
      id: '/_authenticated/debates/$id/edit'
      path: '/edit'
      fullPath: '/debates/$id/edit'
      preLoaderRoute: typeof AuthenticatedDebatesIdEditRouteImport
      parentRoute: typeof AuthenticatedDebatesIdRoute
    }
  }
}

interface AuthenticatedDebatesIdRouteChildren {
  AuthenticatedDebatesIdEditRoute: typeof AuthenticatedDebatesIdEditRoute
  AuthenticatedDebatesIdPresentRoute: typeof AuthenticatedDebatesIdPresentRoute
}

const AuthenticatedDebatesIdRouteChildren: AuthenticatedDebatesIdRouteChildren =
  {
    AuthenticatedDebatesIdEditRoute: AuthenticatedDebatesIdEditRoute,
    AuthenticatedDebatesIdPresentRoute: AuthenticatedDebatesIdPresentRoute,
  }

const AuthenticatedDebatesIdRouteWithChildren =
  AuthenticatedDebatesIdRoute._addFileChildren(
    AuthenticatedDebatesIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedPersonasRoute: typeof AuthenticatedPersonasRoute
  AuthenticatedDebatesIdRoute: typeof AuthenticatedDebatesIdRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedPersonasRoute: AuthenticatedPersonasRoute,
  AuthenticatedDebatesIdRoute: AuthenticatedDebatesIdRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiDebateStreamRoute: ApiDebateStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
