/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVoicesRouteImport } from './routes/_authenticated/voices'
import { Route as AuthenticatedPersonasRouteImport } from './routes/_authenticated/personas'
import { Route as AuthenticatedNewRouteImport } from './routes/_authenticated/new'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiDebateStreamRouteImport } from './routes/api/debate.stream'
import { Route as AuthenticatedPresentationIdRouteImport } from './routes/_authenticated/presentation.$id'
import { Route as AuthenticatedDebatesIdIndexRouteImport } from './routes/_authenticated/debates.$id.index'
import { Route as AuthenticatedDebatesIdEditRouteImport } from './routes/_authenticated/debates.$id.edit'
import { Route as AuthenticatedDebatesIdArenaRouteImport } from './routes/_authenticated/debates.$id.arena'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVoicesRoute = AuthenticatedVoicesRouteImport.update({
  id: '/voices',
  path: '/voices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPersonasRoute = AuthenticatedPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNewRoute = AuthenticatedNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiDebateStreamRoute = ApiDebateStreamRouteImport.update({
  id: '/api/debate/stream',
  path: '/api/debate/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPresentationIdRoute =
  AuthenticatedPresentationIdRouteImport.update({
    id: '/presentation/$id',
    path: '/presentation/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDebatesIdIndexRoute =
  AuthenticatedDebatesIdIndexRouteImport.update({
    id: '/debates/$id/',
    path: '/debates/$id/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDebatesIdEditRoute =
  AuthenticatedDebatesIdEditRouteImport.update({
    id: '/debates/$id/edit',
    path: '/debates/$id/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDebatesIdArenaRoute =
  AuthenticatedDebatesIdArenaRouteImport.update({
    id: '/debates/$id/arena',
    path: '/debates/$id/arena',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new': typeof AuthenticatedNewRoute
  '/personas': typeof AuthenticatedPersonasRoute
  '/voices': typeof AuthenticatedVoicesRoute
  '/presentation/$id': typeof AuthenticatedPresentationIdRoute
  '/api/debate/stream': typeof ApiDebateStreamRoute
  '/debates/$id/arena': typeof AuthenticatedDebatesIdArenaRoute
  '/debates/$id/edit': typeof AuthenticatedDebatesIdEditRoute
  '/debates/$id/': typeof AuthenticatedDebatesIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/new': typeof AuthenticatedNewRoute
  '/personas': typeof AuthenticatedPersonasRoute
  '/voices': typeof AuthenticatedVoicesRoute
  '/presentation/$id': typeof AuthenticatedPresentationIdRoute
  '/api/debate/stream': typeof ApiDebateStreamRoute
  '/debates/$id/arena': typeof AuthenticatedDebatesIdArenaRoute
  '/debates/$id/edit': typeof AuthenticatedDebatesIdEditRoute
  '/debates/$id': typeof AuthenticatedDebatesIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/new': typeof AuthenticatedNewRoute
  '/_authenticated/personas': typeof AuthenticatedPersonasRoute
  '/_authenticated/voices': typeof AuthenticatedVoicesRoute
  '/_authenticated/presentation/$id': typeof AuthenticatedPresentationIdRoute
  '/api/debate/stream': typeof ApiDebateStreamRoute
  '/_authenticated/debates/$id/arena': typeof AuthenticatedDebatesIdArenaRoute
  '/_authenticated/debates/$id/edit': typeof AuthenticatedDebatesIdEditRoute
  '/_authenticated/debates/$id/': typeof AuthenticatedDebatesIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/new'
    | '/personas'
    | '/voices'
    | '/presentation/$id'
    | '/api/debate/stream'
    | '/debates/$id/arena'
    | '/debates/$id/edit'
    | '/debates/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/new'
    | '/personas'
    | '/voices'
    | '/presentation/$id'
    | '/api/debate/stream'
    | '/debates/$id/arena'
    | '/debates/$id/edit'
    | '/debates/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/dashboard'
    | '/_authenticated/new'
    | '/_authenticated/personas'
    | '/_authenticated/voices'
    | '/_authenticated/presentation/$id'
    | '/api/debate/stream'
    | '/_authenticated/debates/$id/arena'
    | '/_authenticated/debates/$id/edit'
    | '/_authenticated/debates/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiDebateStreamRoute: typeof ApiDebateStreamRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/voices': {
      id: '/_authenticated/voices'
      path: '/voices'
      fullPath: '/voices'
      preLoaderRoute: typeof AuthenticatedVoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personas': {
      id: '/_authenticated/personas'
      path: '/personas'
      fullPath: '/personas'
      preLoaderRoute: typeof AuthenticatedPersonasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/new': {
      id: '/_authenticated/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof AuthenticatedNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/debate/stream': {
      id: '/api/debate/stream'
      path: '/api/debate/stream'
      fullPath: '/api/debate/stream'
      preLoaderRoute: typeof ApiDebateStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/presentation/$id': {
      id: '/_authenticated/presentation/$id'
      path: '/presentation/$id'
      fullPath: '/presentation/$id'
      preLoaderRoute: typeof AuthenticatedPresentationIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debates/$id/': {
      id: '/_authenticated/debates/$id/'
      path: '/debates/$id'
      fullPath: '/debates/$id/'
      preLoaderRoute: typeof AuthenticatedDebatesIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debates/$id/edit': {
      id: '/_authenticated/debates/$id/edit'
      path: '/debates/$id/edit'
      fullPath: '/debates/$id/edit'
      preLoaderRoute: typeof AuthenticatedDebatesIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/debates/$id/arena': {
      id: '/_authenticated/debates/$id/arena'
      path: '/debates/$id/arena'
      fullPath: '/debates/$id/arena'
      preLoaderRoute: typeof AuthenticatedDebatesIdArenaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedNewRoute: typeof AuthenticatedNewRoute
  AuthenticatedPersonasRoute: typeof AuthenticatedPersonasRoute
  AuthenticatedVoicesRoute: typeof AuthenticatedVoicesRoute
  AuthenticatedPresentationIdRoute: typeof AuthenticatedPresentationIdRoute
  AuthenticatedDebatesIdArenaRoute: typeof AuthenticatedDebatesIdArenaRoute
  AuthenticatedDebatesIdEditRoute: typeof AuthenticatedDebatesIdEditRoute
  AuthenticatedDebatesIdIndexRoute: typeof AuthenticatedDebatesIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedNewRoute: AuthenticatedNewRoute,
  AuthenticatedPersonasRoute: AuthenticatedPersonasRoute,
  AuthenticatedVoicesRoute: AuthenticatedVoicesRoute,
  AuthenticatedPresentationIdRoute: AuthenticatedPresentationIdRoute,
  AuthenticatedDebatesIdArenaRoute: AuthenticatedDebatesIdArenaRoute,
  AuthenticatedDebatesIdEditRoute: AuthenticatedDebatesIdEditRoute,
  AuthenticatedDebatesIdIndexRoute: AuthenticatedDebatesIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiDebateStreamRoute: ApiDebateStreamRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
